// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: _MyLanguageLexer.flex

package example.parser;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static example.psi.MyLanguageTypes.*;


public class _MyLanguageLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\4\2\22\0\1\1\1\3\1\4\3\0"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\12\17\1\20\1\21\1\22\1\23\1\24"+
    "\2\0\2\25\1\26\2\25\1\27\2\25\1\30\3\25"+
    "\1\31\2\25\1\32\12\25\4\0\1\33\1\0\1\34"+
    "\1\25\1\35\1\25\1\36\1\37\1\40\1\41\1\42"+
    "\2\25\1\43\1\44\1\45\1\46\1\47\1\25\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\3\25\1\56\1\57"+
    "\1\60\7\0\1\2\32\0\1\1\u01df\0\1\1\177\0"+
    "\13\1\35\0\2\2\5\0\1\1\57\0\1\1\240\0"+
    "\1\1\377\0\u0100\61";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\14\23\1\24\1\1"+
    "\1\25\1\26\1\0\1\27\1\30\4\0\1\31\1\0"+
    "\1\32\1\0\1\33\1\34\1\35\1\36\7\23\1\37"+
    "\3\23\1\40\4\0\1\41\1\23\1\42\2\23\1\0"+
    "\5\23\1\43\1\23\1\0\1\44\1\45\1\46\4\23"+
    "\1\47\1\50\1\23\1\51\1\23\1\52\4\23\1\53"+
    "\1\54\1\0\3\23\1\55\1\0\2\23\1\56\1\0"+
    "\2\23\1\0\1\23\1\57\1\60\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\62"+
    "\0\62\0\62\0\62\0\62\0\62\0\62\0\u015e\0\u0190"+
    "\0\62\0\62\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc"+
    "\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c"+
    "\0\u047e\0\62\0\u04b0\0\62\0\62\0\310\0\62\0\62"+
    "\0\u04e2\0\u0514\0\u0546\0\u012c\0\62\0\u0578\0\u05aa\0\u05dc"+
    "\0\62\0\62\0\62\0\62\0\u060e\0\u0640\0\u0672\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u0258\0\u076c\0\u079e\0\u07d0\0\62"+
    "\0\u0802\0\u0834\0\u0866\0\u0898\0\u05dc\0\u08ca\0\u0258\0\u08fc"+
    "\0\u092e\0\u0960\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0258"+
    "\0\u0a8c\0\u0abe\0\62\0\62\0\62\0\u0af0\0\u0b22\0\u0b54"+
    "\0\u0b86\0\u0bb8\0\u0258\0\u0bea\0\u0258\0\u0c1c\0\u0c4e\0\u0c80"+
    "\0\u0cb2\0\u0ce4\0\u0d16\0\u0258\0\u0258\0\u0d48\0\u0d7a\0\u0dac"+
    "\0\u0dde\0\u0258\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a"+
    "\0\u0f3c\0\u0f6e\0\u0fa0\0\u0258\0\62\0\u0258";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\26\1\30"+
    "\1\31\1\32\2\26\1\33\1\34\1\35\2\26\1\36"+
    "\4\26\1\32\2\26\1\37\1\26\1\40\1\41\1\42"+
    "\1\43\1\44\1\2\63\0\2\3\102\0\1\45\36\0"+
    "\4\46\1\47\55\46\5\0\1\50\26\0\1\51\3\0"+
    "\1\52\2\0\1\53\16\0\6\54\1\55\53\54\11\0"+
    "\1\56\4\0\1\57\60\0\1\60\1\0\1\20\65\0"+
    "\1\61\1\62\60\0\1\63\61\0\1\64\55\0\1\26"+
    "\5\0\31\26\23\0\1\26\5\0\21\26\1\65\7\26"+
    "\23\0\1\26\5\0\3\26\1\66\25\26\23\0\1\26"+
    "\5\0\7\26\1\67\21\26\23\0\1\26\5\0\7\26"+
    "\1\70\21\26\23\0\1\26\5\0\21\26\1\71\7\26"+
    "\23\0\1\26\5\0\16\26\1\72\12\26\23\0\1\26"+
    "\5\0\7\26\1\73\21\26\23\0\1\26\5\0\12\26"+
    "\1\74\16\26\23\0\1\26\5\0\23\26\1\75\5\26"+
    "\23\0\1\26\5\0\7\26\1\76\21\26\23\0\1\26"+
    "\5\0\14\26\1\77\14\26\63\0\1\100\46\0\1\101"+
    "\67\0\1\102\61\0\1\103\7\0\11\56\1\104\50\56"+
    "\2\57\1\0\56\57\20\0\1\105\61\0\1\26\5\0"+
    "\20\26\1\106\10\26\23\0\1\26\5\0\2\26\1\107"+
    "\26\26\23\0\1\26\5\0\10\26\1\110\20\26\23\0"+
    "\1\26\5\0\23\26\1\111\5\26\21\0\1\112\1\0"+
    "\1\26\5\0\17\26\1\113\1\114\10\26\23\0\1\26"+
    "\5\0\24\26\1\115\4\26\23\0\1\26\5\0\16\26"+
    "\1\116\12\26\23\0\1\26\5\0\26\26\1\117\2\26"+
    "\23\0\1\26\5\0\23\26\1\120\5\26\23\0\1\26"+
    "\5\0\15\26\1\121\13\26\53\0\1\122\33\0\1\123"+
    "\61\0\1\124\40\0\11\56\1\104\4\56\1\125\43\56"+
    "\17\0\1\26\5\0\12\26\1\126\12\26\1\127\3\26"+
    "\23\0\1\26\5\0\23\26\1\130\5\26\23\0\1\26"+
    "\5\0\11\26\1\131\17\26\31\0\31\132\21\0\1\112"+
    "\1\0\1\26\5\0\17\26\1\113\11\26\23\0\1\26"+
    "\5\0\25\26\1\127\3\26\23\0\1\26\5\0\11\26"+
    "\1\133\17\26\23\0\1\26\5\0\24\26\1\134\4\26"+
    "\23\0\1\26\5\0\11\26\1\135\17\26\23\0\1\26"+
    "\5\0\16\26\1\136\12\26\25\0\1\137\57\0\1\26"+
    "\5\0\15\26\1\140\13\26\23\0\1\26\5\0\7\26"+
    "\1\141\21\26\23\0\1\26\5\0\21\26\1\142\7\26"+
    "\23\0\1\26\5\0\20\26\1\143\10\26\21\0\1\112"+
    "\1\0\1\132\5\0\31\132\23\0\1\26\5\0\11\26"+
    "\1\144\17\26\23\0\1\26\5\0\11\26\1\145\17\26"+
    "\11\0\1\146\73\0\1\26\5\0\23\26\1\147\5\26"+
    "\23\0\1\26\5\0\15\26\1\150\13\26\23\0\1\26"+
    "\5\0\6\26\1\151\22\26\23\0\1\26\5\0\25\26"+
    "\1\152\3\26\40\0\1\153\44\0\1\26\5\0\17\26"+
    "\1\154\11\26\23\0\1\26\5\0\20\26\1\155\10\26"+
    "\23\0\1\26\5\0\31\156\50\0\1\157\34\0\1\26"+
    "\5\0\4\26\1\160\24\26\23\0\1\26\5\0\11\26"+
    "\1\161\17\26\23\0\1\156\5\0\31\156\53\0\1\162"+
    "\31\0\1\26\5\0\24\26\1\163\4\26\23\0\1\26"+
    "\5\0\23\26\1\164\5\26\25\0\1\165\57\0\1\26"+
    "\5\0\13\26\1\166\15\26\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4050];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\7\11\2\1\2\11\17\1\1\11"+
    "\1\1\2\11\1\0\2\11\4\0\1\11\1\0\1\1"+
    "\1\0\4\11\13\1\1\11\4\0\5\1\1\0\7\1"+
    "\1\0\3\11\20\1\1\0\4\1\1\0\3\1\1\0"+
    "\2\1\1\0\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  public _MyLanguageLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _MyLanguageLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 50: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 51: break;
          case 3:
            { return NOT_OP;
            }
          // fall through
          case 52: break;
          case 4:
            { return AMPERSAND;
            }
          // fall through
          case 53: break;
          case 5:
            { return LPAREN;
            }
          // fall through
          case 54: break;
          case 6:
            { return RPAREN;
            }
          // fall through
          case 55: break;
          case 7:
            { return MUL;
            }
          // fall through
          case 56: break;
          case 8:
            { return PLUS;
            }
          // fall through
          case 57: break;
          case 9:
            { return COMMA;
            }
          // fall through
          case 58: break;
          case 10:
            { return MINUS;
            }
          // fall through
          case 59: break;
          case 11:
            { return DOT;
            }
          // fall through
          case 60: break;
          case 12:
            { return DIV;
            }
          // fall through
          case 61: break;
          case 13:
            { return INTEGER_NUMBER;
            }
          // fall through
          case 62: break;
          case 14:
            { return COLON;
            }
          // fall through
          case 63: break;
          case 15:
            { return SEMICOLON;
            }
          // fall through
          case 64: break;
          case 16:
            { return LESS;
            }
          // fall through
          case 65: break;
          case 17:
            { return EQ;
            }
          // fall through
          case 66: break;
          case 18:
            { return GREATER;
            }
          // fall through
          case 67: break;
          case 19:
            { return IDENTIFIER;
            }
          // fall through
          case 68: break;
          case 20:
            { return LBRACE;
            }
          // fall through
          case 69: break;
          case 21:
            { return RBRACE;
            }
          // fall through
          case 70: break;
          case 22:
            { return NOT_EQUAL;
            }
          // fall through
          case 71: break;
          case 23:
            { return DOUBLE_QUOTED_STRING;
            }
          // fall through
          case 72: break;
          case 24:
            { return AND_OP;
            }
          // fall through
          case 73: break;
          case 25:
            { return SINGLE_QUOTED_STRING;
            }
          // fall through
          case 74: break;
          case 26:
            { return LINE_COMMENT;
            }
          // fall through
          case 75: break;
          case 27:
            { return LESS_EQUAL;
            }
          // fall through
          case 76: break;
          case 28:
            { return NOT_EQUAL_ALT;
            }
          // fall through
          case 77: break;
          case 29:
            { return EQUAL_EQUAL;
            }
          // fall through
          case 78: break;
          case 30:
            { return GREATER_EQUAL;
            }
          // fall through
          case 79: break;
          case 31:
            { return IF_KEYWORD;
            }
          // fall through
          case 80: break;
          case 32:
            { return OR_OP;
            }
          // fall through
          case 81: break;
          case 33:
            { return DECIMAL_NUMBER;
            }
          // fall through
          case 82: break;
          case 34:
            { return IIF_KEYWORD;
            }
          // fall through
          case 83: break;
          case 35:
            { return VAR_KEYWORD;
            }
          // fall through
          case 84: break;
          case 36:
            { return GT_ENTITY;
            }
          // fall through
          case 85: break;
          case 37:
            { return LT_ENTITY;
            }
          // fall through
          case 86: break;
          case 38:
            { return BLOCK_COMMENT;
            }
          // fall through
          case 87: break;
          case 39:
            { return JAVA_PATH_IDENTIFIER;
            }
          // fall through
          case 88: break;
          case 40:
            { return ELSE_KEYWORD;
            }
          // fall through
          case 89: break;
          case 41:
            { return TRUE_KEYWORD;
            }
          // fall through
          case 90: break;
          case 42:
            { return AMP_ENTITY;
            }
          // fall through
          case 91: break;
          case 43:
            { return FALSE_KEYWORD;
            }
          // fall through
          case 92: break;
          case 44:
            { return WHILE_KEYWORD;
            }
          // fall through
          case 93: break;
          case 45:
            { return PARENT_KEYWORD;
            }
          // fall through
          case 94: break;
          case 46:
            { return MACRO_IDENTIFIER;
            }
          // fall through
          case 95: break;
          case 47:
            { return CONTAINER_KEYWORD;
            }
          // fall through
          case 96: break;
          case 48:
            { return AND_OP_ENTITY;
            }
          // fall through
          case 97: break;
          case 49:
            { return CONFIRM_MSG;
            }
          // fall through
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
