// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: _MyLanguageLexer.flex

package example.parser;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static example.psi.MyLanguageTypes.*;


public class _MyLanguageLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\22\0\1\1\1\2\1\3\3\0\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\12\16\1\0\1\17\1\20\1\21\1\22\2\0"+
    "\2\23\1\24\2\23\1\25\2\23\1\26\3\23\1\27"+
    "\2\23\1\30\12\23\4\0\1\31\1\0\1\32\1\23"+
    "\1\33\1\23\1\34\1\35\1\36\1\37\1\40\2\23"+
    "\1\41\1\42\1\43\1\44\1\45\1\23\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\3\23\1\54\1\55\1\56"+
    "\7\0\1\1\32\0\1\1\u01df\0\1\1\177\0\13\1"+
    "\35\0\2\1\5\0\1\1\57\0\1\1\240\0\1\1"+
    "\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\14\22\1\23\1\1\1\24"+
    "\1\25\1\0\1\26\1\27\4\0\1\30\1\31\1\32"+
    "\1\33\1\34\7\22\1\35\3\22\1\36\3\0\1\22"+
    "\1\37\2\22\1\0\4\22\1\40\1\22\1\0\1\41"+
    "\1\42\3\22\1\43\1\44\1\22\1\45\1\22\1\46"+
    "\3\22\1\47\1\50\1\0\2\22\1\51\1\0\1\22"+
    "\1\52\1\0\1\22\1\0\1\53\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\57\0\u0149"+
    "\0\57\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a"+
    "\0\57\0\u0439\0\57\0\57\0\274\0\57\0\57\0\u0468"+
    "\0\u0497\0\u04c6\0\u011a\0\57\0\57\0\57\0\57\0\57"+
    "\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u0205"+
    "\0\u063e\0\u066d\0\u069c\0\57\0\u06cb\0\u06fa\0\u0729\0\u0758"+
    "\0\u0205\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1"+
    "\0\u0205\0\u08d0\0\u08ff\0\57\0\57\0\u092e\0\u095d\0\u098c"+
    "\0\u09bb\0\u0205\0\u09ea\0\u0205\0\u0a19\0\u0a48\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0205\0\u0205\0\u0b04\0\u0b33\0\u0b62\0\u0205\0\u0b91"+
    "\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0205\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\25\1\27\1\30"+
    "\1\31\2\25\1\32\1\33\1\34\2\25\1\35\4\25"+
    "\1\31\2\25\1\36\1\25\1\37\1\40\1\41\1\42"+
    "\1\43\60\0\1\3\76\0\1\44\35\0\3\45\1\46"+
    "\53\45\4\0\1\47\25\0\1\50\3\0\1\51\2\0"+
    "\1\52\15\0\5\53\1\54\51\53\16\0\1\20\61\0"+
    "\1\55\1\56\55\0\1\57\56\0\1\60\53\0\1\25"+
    "\4\0\31\25\21\0\1\25\4\0\21\25\1\61\7\25"+
    "\21\0\1\25\4\0\3\25\1\62\25\25\21\0\1\25"+
    "\4\0\7\25\1\63\21\25\21\0\1\25\4\0\7\25"+
    "\1\64\21\25\21\0\1\25\4\0\21\25\1\65\7\25"+
    "\21\0\1\25\4\0\16\25\1\66\12\25\21\0\1\25"+
    "\4\0\7\25\1\67\21\25\21\0\1\25\4\0\12\25"+
    "\1\70\16\25\21\0\1\25\4\0\23\25\1\71\5\25"+
    "\21\0\1\25\4\0\7\25\1\72\21\25\21\0\1\25"+
    "\4\0\14\25\1\73\14\25\60\0\1\74\43\0\1\75"+
    "\64\0\1\76\56\0\1\77\24\0\1\25\4\0\20\25"+
    "\1\100\10\25\21\0\1\25\4\0\2\25\1\101\26\25"+
    "\21\0\1\25\4\0\10\25\1\102\20\25\21\0\1\25"+
    "\4\0\23\25\1\103\5\25\17\0\1\104\1\0\1\25"+
    "\4\0\17\25\1\105\1\100\10\25\21\0\1\25\4\0"+
    "\24\25\1\106\4\25\21\0\1\25\4\0\16\25\1\107"+
    "\12\25\21\0\1\25\4\0\26\25\1\110\2\25\21\0"+
    "\1\25\4\0\23\25\1\111\5\25\21\0\1\25\4\0"+
    "\15\25\1\112\13\25\50\0\1\113\30\0\1\114\56\0"+
    "\1\115\55\0\1\25\4\0\25\25\1\116\3\25\21\0"+
    "\1\25\4\0\23\25\1\117\5\25\21\0\1\25\4\0"+
    "\11\25\1\120\17\25\26\0\31\121\17\0\1\104\1\0"+
    "\1\25\4\0\17\25\1\105\11\25\21\0\1\25\4\0"+
    "\11\25\1\122\17\25\21\0\1\25\4\0\24\25\1\123"+
    "\4\25\21\0\1\25\4\0\11\25\1\124\17\25\21\0"+
    "\1\25\4\0\16\25\1\125\12\25\22\0\1\126\55\0"+
    "\1\25\4\0\7\25\1\127\21\25\21\0\1\25\4\0"+
    "\21\25\1\130\7\25\21\0\1\25\4\0\20\25\1\131"+
    "\10\25\17\0\1\104\1\0\1\121\4\0\31\121\21\0"+
    "\1\25\4\0\11\25\1\132\17\25\21\0\1\25\4\0"+
    "\11\25\1\133\17\25\7\0\1\134\70\0\1\25\4\0"+
    "\15\25\1\135\13\25\21\0\1\25\4\0\6\25\1\136"+
    "\22\25\21\0\1\25\4\0\25\25\1\137\3\25\35\0"+
    "\1\140\42\0\1\25\4\0\20\25\1\141\10\25\21\0"+
    "\1\25\4\0\31\142\45\0\1\143\32\0\1\25\4\0"+
    "\11\25\1\144\17\25\21\0\1\142\4\0\31\142\50\0"+
    "\1\145\27\0\1\25\4\0\23\25\1\146\5\25\22\0"+
    "\1\147\37\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3243];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\10\11\1\1\1\11\17\1\1\11"+
    "\1\1\2\11\1\0\2\11\4\0\5\11\13\1\1\11"+
    "\3\0\4\1\1\0\6\1\1\0\2\11\16\1\1\0"+
    "\3\1\1\0\2\1\1\0\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  public _MyLanguageLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _MyLanguageLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 45: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 46: break;
          case 3:
            { return NOT_OP;
            }
          // fall through
          case 47: break;
          case 4:
            { return AMPERSAND;
            }
          // fall through
          case 48: break;
          case 5:
            { return LPAREN;
            }
          // fall through
          case 49: break;
          case 6:
            { return RPAREN;
            }
          // fall through
          case 50: break;
          case 7:
            { return MUL;
            }
          // fall through
          case 51: break;
          case 8:
            { return PLUS;
            }
          // fall through
          case 52: break;
          case 9:
            { return COMMA;
            }
          // fall through
          case 53: break;
          case 10:
            { return MINUS;
            }
          // fall through
          case 54: break;
          case 11:
            { return DOT;
            }
          // fall through
          case 55: break;
          case 12:
            { return DIV;
            }
          // fall through
          case 56: break;
          case 13:
            { return NUMBER;
            }
          // fall through
          case 57: break;
          case 14:
            { return SEMICOLON;
            }
          // fall through
          case 58: break;
          case 15:
            { return LESS;
            }
          // fall through
          case 59: break;
          case 16:
            { return EQ;
            }
          // fall through
          case 60: break;
          case 17:
            { return GREATER;
            }
          // fall through
          case 61: break;
          case 18:
            { return IDENTIFIER;
            }
          // fall through
          case 62: break;
          case 19:
            { return LBRACE;
            }
          // fall through
          case 63: break;
          case 20:
            { return RBRACE;
            }
          // fall through
          case 64: break;
          case 21:
            { return NOT_EQUAL;
            }
          // fall through
          case 65: break;
          case 22:
            { return DOUBLE_QUOTED_STRING;
            }
          // fall through
          case 66: break;
          case 23:
            { return AND_OP;
            }
          // fall through
          case 67: break;
          case 24:
            { return SINGLE_QUOTED_STRING;
            }
          // fall through
          case 68: break;
          case 25:
            { return LESS_EQUAL;
            }
          // fall through
          case 69: break;
          case 26:
            { return NOT_EQUAL_ALT;
            }
          // fall through
          case 70: break;
          case 27:
            { return EQUAL_EQUAL;
            }
          // fall through
          case 71: break;
          case 28:
            { return GREATER_EQUAL;
            }
          // fall through
          case 72: break;
          case 29:
            { return IF_KEYWORD;
            }
          // fall through
          case 73: break;
          case 30:
            { return OR_OP;
            }
          // fall through
          case 74: break;
          case 31:
            { return IIF_KEYWORD;
            }
          // fall through
          case 75: break;
          case 32:
            { return VAR_KEYWORD;
            }
          // fall through
          case 76: break;
          case 33:
            { return GT_ENTITY;
            }
          // fall through
          case 77: break;
          case 34:
            { return LT_ENTITY;
            }
          // fall through
          case 78: break;
          case 35:
            { return JAVA_PATH_IDENTIFIER;
            }
          // fall through
          case 79: break;
          case 36:
            { return ELSE_KEYWORD;
            }
          // fall through
          case 80: break;
          case 37:
            { return TRUE_KEYWORD;
            }
          // fall through
          case 81: break;
          case 38:
            { return AMP_ENTITY;
            }
          // fall through
          case 82: break;
          case 39:
            { return FALSE_KEYWORD;
            }
          // fall through
          case 83: break;
          case 40:
            { return WHILE_KEYWORD;
            }
          // fall through
          case 84: break;
          case 41:
            { return PARENT_KEYWORD;
            }
          // fall through
          case 85: break;
          case 42:
            { return MACRO_IDENTIFIER;
            }
          // fall through
          case 86: break;
          case 43:
            { return CONTAINER_KEYWORD;
            }
          // fall through
          case 87: break;
          case 44:
            { return AND_OP_ENTITY;
            }
          // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
